// Minnesota-specific cost database for rehab items
// Costs are ranges: [low, high] per unit

export interface CostItem {
  key: string;
  category: string;
  name: string;
  unit: string;
  costLow: number;
  costHigh: number;
  laborPct: number;
  priority: "essential" | "high-roi" | "recommended" | "optional";
  defaultQuantity?: number;
}

export const COST_DATABASE: CostItem[] = [
  // Kitchen
  {
    key: "cabinet_replacement_full",
    category: "Kitchen",
    name: "Cabinet Replacement (Full)",
    unit: "LF",
    costLow: 280,
    costHigh: 350,
    laborPct: 40,
    priority: "recommended",
    defaultQuantity: 30,
  },
  {
    key: "countertop_laminate",
    category: "Kitchen",
    name: "Laminate Countertops",
    unit: "sqft",
    costLow: 15,
    costHigh: 40,
    laborPct: 30,
    priority: "optional",
    defaultQuantity: 40,
  },
  {
    key: "countertop_quartz",
    category: "Kitchen",
    name: "Quartz Countertops",
    unit: "sqft",
    costLow: 55,
    costHigh: 80,
    laborPct: 35,
    priority: "high-roi",
    defaultQuantity: 40,
  },
  {
    key: "countertop_granite",
    category: "Kitchen",
    name: "Granite Countertops",
    unit: "sqft",
    costLow: 40,
    costHigh: 60,
    laborPct: 35,
    priority: "recommended",
    defaultQuantity: 40,
  },
  {
    key: "appliance_refrigerator",
    category: "Kitchen",
    name: "Refrigerator (Stainless)",
    unit: "each",
    costLow: 800,
    costHigh: 1500,
    laborPct: 5,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "appliance_range",
    category: "Kitchen",
    name: "Range/Oven (Stainless)",
    unit: "each",
    costLow: 600,
    costHigh: 1200,
    laborPct: 5,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "appliance_dishwasher",
    category: "Kitchen",
    name: "Dishwasher (Stainless)",
    unit: "each",
    costLow: 400,
    costHigh: 800,
    laborPct: 10,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "appliance_microwave",
    category: "Kitchen",
    name: "Over-Range Microwave",
    unit: "each",
    costLow: 200,
    costHigh: 400,
    laborPct: 15,
    priority: "optional",
    defaultQuantity: 1,
  },

  // Flooring
  {
    key: "flooring_lvp",
    category: "Interior",
    name: "LVP Flooring",
    unit: "sqft",
    costLow: 4,
    costHigh: 8,
    laborPct: 50,
    priority: "high-roi",
    defaultQuantity: 200,
  },
  {
    key: "flooring_lvp_main",
    category: "Interior",
    name: "LVP Flooring (Main Areas)",
    unit: "sqft",
    costLow: 4,
    costHigh: 8,
    laborPct: 50,
    priority: "high-roi",
    defaultQuantity: 1000,
  },
  {
    key: "flooring_tile",
    category: "Interior",
    name: "Tile Flooring",
    unit: "sqft",
    costLow: 8,
    costHigh: 15,
    laborPct: 60,
    priority: "recommended",
    defaultQuantity: 100,
  },
  {
    key: "flooring_tile_bath",
    category: "Bathrooms",
    name: "Tile Flooring (Bathroom)",
    unit: "sqft",
    costLow: 10,
    costHigh: 18,
    laborPct: 60,
    priority: "recommended",
    defaultQuantity: 50,
  },
  {
    key: "flooring_lvp_bath",
    category: "Bathrooms",
    name: "LVP Flooring (Bathroom)",
    unit: "sqft",
    costLow: 5,
    costHigh: 9,
    laborPct: 50,
    priority: "optional",
    defaultQuantity: 50,
  },
  {
    key: "flooring_hardwood",
    category: "Interior",
    name: "Hardwood Flooring",
    unit: "sqft",
    costLow: 8,
    costHigh: 14,
    laborPct: 55,
    priority: "high-roi",
    defaultQuantity: 200,
  },
  {
    key: "flooring_hardwood_main",
    category: "Interior",
    name: "Hardwood Flooring (Main Areas)",
    unit: "sqft",
    costLow: 8,
    costHigh: 14,
    laborPct: 55,
    priority: "high-roi",
    defaultQuantity: 1000,
  },
  {
    key: "flooring_carpet",
    category: "Interior",
    name: "Carpet (Bedrooms)",
    unit: "sqft",
    costLow: 3,
    costHigh: 6,
    laborPct: 40,
    priority: "optional",
    defaultQuantity: 400,
  },

  // Bathrooms
  {
    key: "bathroom_vanity",
    category: "Bathrooms",
    name: "Vanity w/ Top & Faucet",
    unit: "each",
    costLow: 400,
    costHigh: 800,
    laborPct: 25,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "bathroom_toilet",
    category: "Bathrooms",
    name: "Toilet Replacement",
    unit: "each",
    costLow: 200,
    costHigh: 400,
    laborPct: 30,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "bathroom_surround",
    category: "Bathrooms",
    name: "Tub/Shower Surround",
    unit: "each",
    costLow: 800,
    costHigh: 1500,
    laborPct: 50,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "bathroom_tile_shower",
    category: "Bathrooms",
    name: "Tiled Shower",
    unit: "each",
    costLow: 2500,
    costHigh: 4500,
    laborPct: 65,
    priority: "high-roi",
    defaultQuantity: 1,
  },
  {
    key: "bathroom_full_shower",
    category: "Bathrooms",
    name: "Full Tub/Shower Replacement",
    unit: "each",
    costLow: 1500,
    costHigh: 3000,
    laborPct: 55,
    priority: "recommended",
    defaultQuantity: 1,
  },

  // Paint
  {
    key: "paint_touchup",
    category: "Interior",
    name: "Paint Touch-up",
    unit: "LS",
    costLow: 500,
    costHigh: 1000,
    laborPct: 80,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "paint_full_interior",
    category: "Interior",
    name: "Full Interior Paint",
    unit: "sqft",
    costLow: 1.5,
    costHigh: 2.5,
    laborPct: 75,
    priority: "high-roi",
    defaultQuantity: 2000,
  },
  {
    key: "paint_exterior",
    category: "Exterior",
    name: "Exterior Paint",
    unit: "LS",
    costLow: 3000,
    costHigh: 6000,
    laborPct: 70,
    priority: "recommended",
    defaultQuantity: 1,
  },

  // Trim & Doors
  {
    key: "trim_paint",
    category: "Interior",
    name: "Paint Existing Trim",
    unit: "LF",
    costLow: 2,
    costHigh: 4,
    laborPct: 80,
    priority: "optional",
    defaultQuantity: 400,
  },
  {
    key: "trim_replace",
    category: "Interior",
    name: "Replace Baseboards",
    unit: "LF",
    costLow: 4,
    costHigh: 8,
    laborPct: 50,
    priority: "optional",
    defaultQuantity: 400,
  },
  {
    key: "door_hardware",
    category: "Interior",
    name: "Door Hardware",
    unit: "each",
    costLow: 25,
    costHigh: 50,
    laborPct: 20,
    priority: "optional",
    defaultQuantity: 15,
  },
  {
    key: "door_interior",
    category: "Interior",
    name: "Interior Door w/ Hardware",
    unit: "each",
    costLow: 150,
    costHigh: 300,
    laborPct: 40,
    priority: "optional",
    defaultQuantity: 15,
  },
  {
    key: "door_entry",
    category: "Exterior",
    name: "Entry Door",
    unit: "each",
    costLow: 800,
    costHigh: 2000,
    laborPct: 30,
    priority: "high-roi",
    defaultQuantity: 1,
  },

  // Lighting
  {
    key: "lighting_fixtures",
    category: "Interior",
    name: "Light Fixture Package",
    unit: "LS",
    costLow: 500,
    costHigh: 1500,
    laborPct: 30,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "lighting_recessed",
    category: "Interior",
    name: "Recessed Lighting Package",
    unit: "LS",
    costLow: 800,
    costHigh: 2000,
    laborPct: 60,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "electrical_switches",
    category: "Interior",
    name: "Update Switches/Outlets",
    unit: "LS",
    costLow: 300,
    costHigh: 600,
    laborPct: 50,
    priority: "optional",
    defaultQuantity: 1,
  },

  // Exterior
  {
    key: "roof_repair",
    category: "Exterior",
    name: "Roof Repairs",
    unit: "LS",
    costLow: 500,
    costHigh: 2000,
    laborPct: 70,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "roof_replacement",
    category: "Exterior",
    name: "Roof Replacement",
    unit: "sqft",
    costLow: 4,
    costHigh: 8,
    laborPct: 60,
    priority: "essential",
    defaultQuantity: 2000,
  },
  {
    key: "siding_repair",
    category: "Exterior",
    name: "Siding Repairs",
    unit: "LS",
    costLow: 500,
    costHigh: 2000,
    laborPct: 65,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "siding_replacement",
    category: "Exterior",
    name: "Siding Replacement",
    unit: "sqft",
    costLow: 6,
    costHigh: 12,
    laborPct: 55,
    priority: "recommended",
    defaultQuantity: 1500,
  },
  {
    key: "windows_partial",
    category: "Exterior",
    name: "Window Replacement (Partial)",
    unit: "LS",
    costLow: 2000,
    costHigh: 5000,
    laborPct: 40,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "windows_full",
    category: "Exterior",
    name: "Window Replacement",
    unit: "each",
    costLow: 400,
    costHigh: 800,
    laborPct: 40,
    priority: "recommended",
    defaultQuantity: 15,
  },
  {
    key: "landscaping_cleanup",
    category: "Exterior",
    name: "Landscaping Cleanup",
    unit: "LS",
    costLow: 300,
    costHigh: 800,
    laborPct: 90,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "landscaping_mulch",
    category: "Exterior",
    name: "Mulch & Bed Refresh",
    unit: "LS",
    costLow: 400,
    costHigh: 1000,
    laborPct: 60,
    priority: "high-roi",
    defaultQuantity: 1,
  },
  {
    key: "landscaping_sod",
    category: "Exterior",
    name: "New Sod/Lawn",
    unit: "LS",
    costLow: 1500,
    costHigh: 4000,
    laborPct: 50,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "landscaping_plants",
    category: "Exterior",
    name: "Plants & Shrubs",
    unit: "LS",
    costLow: 500,
    costHigh: 1500,
    laborPct: 40,
    priority: "optional",
    defaultQuantity: 1,
  },

  // Systems
  {
    key: "hvac_service",
    category: "Systems",
    name: "HVAC Service/Tune-up",
    unit: "LS",
    costLow: 150,
    costHigh: 400,
    laborPct: 90,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "hvac_replacement",
    category: "Systems",
    name: "HVAC System Replacement",
    unit: "LS",
    costLow: 6000,
    costHigh: 12000,
    laborPct: 40,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "water_heater",
    category: "Systems",
    name: "Water Heater Replacement",
    unit: "each",
    costLow: 800,
    costHigh: 1500,
    laborPct: 35,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "electrical_panel",
    category: "Systems",
    name: "Electrical Panel Upgrade",
    unit: "LS",
    costLow: 1500,
    costHigh: 3500,
    laborPct: 70,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "electrical_outlets",
    category: "Systems",
    name: "Add/Update Outlets",
    unit: "LS",
    costLow: 500,
    costHigh: 1500,
    laborPct: 70,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "electrical_rewire",
    category: "Systems",
    name: "Partial Rewire",
    unit: "LS",
    costLow: 3000,
    costHigh: 8000,
    laborPct: 75,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "plumbing_fixtures",
    category: "Systems",
    name: "Plumbing Fixture Updates",
    unit: "LS",
    costLow: 500,
    costHigh: 1500,
    laborPct: 50,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "plumbing_repipe",
    category: "Systems",
    name: "Partial Repipe",
    unit: "LS",
    costLow: 2000,
    costHigh: 6000,
    laborPct: 70,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "plumbing_sewer",
    category: "Systems",
    name: "Sewer Line Repair",
    unit: "LS",
    costLow: 2000,
    costHigh: 8000,
    laborPct: 75,
    priority: "essential",
    defaultQuantity: 1,
  },

  // Basement
  {
    key: "basement_finish_basic",
    category: "Basement",
    name: "Basic Basement Finish",
    unit: "sqft",
    costLow: 25,
    costHigh: 40,
    laborPct: 55,
    priority: "optional",
    defaultQuantity: 800,
  },
  {
    key: "basement_finish_full",
    category: "Basement",
    name: "Full Basement Finish",
    unit: "sqft",
    costLow: 40,
    costHigh: 65,
    laborPct: 55,
    priority: "optional",
    defaultQuantity: 800,
  },
  {
    key: "basement_bathroom",
    category: "Basement",
    name: "Basement Bathroom",
    unit: "each",
    costLow: 8000,
    costHigh: 15000,
    laborPct: 60,
    priority: "optional",
    defaultQuantity: 1,
  },
  {
    key: "basement_sealing",
    category: "Basement",
    name: "Basement Sealing",
    unit: "LS",
    costLow: 500,
    costHigh: 1500,
    laborPct: 70,
    priority: "recommended",
    defaultQuantity: 1,
  },
  {
    key: "basement_waterproofing",
    category: "Basement",
    name: "Full Waterproofing",
    unit: "LS",
    costLow: 5000,
    costHigh: 15000,
    laborPct: 65,
    priority: "essential",
    defaultQuantity: 1,
  },
  {
    key: "basement_egress",
    category: "Basement",
    name: "Egress Window",
    unit: "each",
    costLow: 3000,
    costHigh: 6000,
    laborPct: 55,
    priority: "essential",
    defaultQuantity: 1,
  },
];

export function getCostItem(key: string): CostItem | undefined {
  return COST_DATABASE.find((item) => item.key === key);
}

export function getCostItemsByCategory(category: string): CostItem[] {
  return COST_DATABASE.filter((item) => item.category === category);
}

